### ISSUE TITLE
Using this on datepicker does not change highlight on change of month

### ISSUE THREAD

**Issue by waratah** [spongessuck/gm.datepickerMultiSelect#18]
I included this into ui-bootstrap 0.10.0 by registering on datepicker:
 var delegate = [ '$delegate', function($delegate) {...}];
$provide.decorator('datepickerDirective', delegate);
$provide.decorator('datepickerPopupDirective', delegate);

Works fine except for when you select a range and change the month.  Because you are hooking the change of the ngmodel and it is not updating it will not redraw the selected days as highlighted.
This needs to hook up to the month change and I am currently unable to work out how to tap into that month change click calling refill.

Any assistance would be appreciated.

**Comment by spongessuck** [comment]
Why do you need to use UI Bootstrap 0.10?

**Comment by waratah** [comment]
Pretty sure this issue is not release related.   (I am pretty locked into that release at present).
The issue is that you are highlighting on change of ng model and changing the month does not update the model, hence the highlighting is not actioned.   I could not find an obvious hook to reapply the date.selected on the model when the month is changed.

Note that I am overriding datepicker not day picker.

**Comment by spongessuck** [comment]
I just never tested it on 0.10.

Why are you overriding datepicker and not daypicker? Daypicker is the subcomponent in the datepicker module that controls the view for picking individual days.

What is this for?

    var delegate = [ '$delegate', function($delegate) {...}];
    $provide.decorator('datepickerDirective', delegate);
    $provide.decorator('datepickerPopupDirective', delegate);

Can you post a demo?

**Comment by spongessuck** [comment]
Also, I'm not highlighting when the model changes, I'm highlighting when the activeDate in the controller changes, which happens whether you select a date or switch months.

See from lines 49 in src/:

					/* Fires when date is selected or when month is changed. */
					scope.$watch(function () {
						return ctrl.activeDate.getTime();
					}, update);

**Comment by waratah** [comment]
Please update docs to say that you require 0.11 version or higher.   Does not work with 0.10.   We  have raised a task to update the libraries.

So thanks for you help and close this issue.
