### ISSUE TITLE
Highlight multiple days but select only one day

### ISSUE THREAD

**Issue by waqas-syed** [spongessuck/gm.datepickerMultiSelect#19]
I want to be able to highlight a number of days based on some business logic when the datepicker gets rendered on screen but the user be only able to select one day. So that will probably require that the highlighted days be in a different color(e.g., green) and the selected single day be in another color (e.g., red).

Is this possible? Or even if I can make some edits in the current code to achieve this that would be great!

**Comment by spongessuck** [comment]
I don't think this directive is what you need: I would implement the date-disabled property on Datepicker, which lets you run the date through a function to see if it should be enabled or not, and then change the CSS for the active dates and selected dates to get the colors you want.
