### ISSUE TITLE
how to clear the selected dates in individual mode

### ISSUE THREAD

**Issue by bakyaxplore** [spongessuck/gm.datepickerMultiSelect#20]
I am using this datepicker on a modal popup and the modal popup will get open when a button click.Every time the button clicks, the selected dates of the datepicker have to clear and the selected dates should be empty. Plz help me to clear the selected dates and to reset the background of selected button to normal mode.

**Comment by spongessuck** [comment]
Just reset the model, i.e. `$scope.selectedDates = [];`

**Comment by bakyaxplore** [comment]
I'm actually new to angular js will u plz post the complete syntax. I tried like this 

$("#button").click(function () {
    angular.module('app', ['gm.datepickerMultiSelect'])
    .controller('AppCtrl', function ($scope, $http) {
        this.selectedDates = [];
    });
});

But its not working. Plz help me.

**Comment by spongessuck** [comment]
I won't write your program for you, but I will tell you that you're doing it completely wrong. Please read the AngularJS documentation to find out how to create an Angular app and use controllers.

**Comment by bakyaxplore** [comment]
Sorry for the inconvenience.
Will u plz tell me after did that selecteddates = []
how to made it to reflect in datepicker ie., removing the all the
selected dates in selected dates area along with remove button and how
to deselect the buttons in calendar.
I got confused that  after clearing the selecteddates the datepicker
is not refreshed by clearing the selected dates in selected dates div
and deselecting the dates in picker.

how to refresh the datepicker after the selected dates=[].

**Comment by spongessuck** [comment]
If your controller and model is set up correctly, simply resetting your model (i.e. selectedDates = []) will automatically remove all of the selected dates in the selected dates area and deselect the buttons in the calendar - that's the beauty of Angular! You don't need to interact directly with the DOM like jQuery.

Please take a look at the following page to learn more about the basics of Angular:

https://www.codeschool.com/courses/shaping-up-with-angular-js
