### ISSUE TITLE
How to add events like the standard date picker 

### ISSUE THREAD

**Issue by pucchur** [spongessuck/gm.datepickerMultiSelect#25]
How to add events in this date picker like the standard one.

 $scope.events =
    [
      {
        date: tomorrow,
        status: 'full'
      },
      {
        date: afterTomorrow,
        status: 'partially'
      }
    ];

**Comment by spongessuck** [comment]
That's not a feature in this module. What do you mean by the 'standard' datepicker?

**Comment by pucchur** [comment]
I mean as available in this datepicker https://github.com/angular-ui/bootstrap/tree/master/src/datepicker

**Comment by spongessuck** [comment]
Looks like you need to implement a function for the `custom-class` attribute to make certain days look different based on logic.

    <uib-datepicker ... custom-class="getDayClass(date, mode)">

Check the [example](https://angular-ui.github.io/bootstrap/#/datepicker) for how to use it.
