### ISSUE TITLE
How to access the range dates in the controller

### ISSUE THREAD

**Issue by pucchur** [spongessuck/gm.datepickerMultiSelect#26]
Apologies for the dumb question but I am not able to access the dates in the controller AppCtrl from this example http://plnkr.co/edit/KMxadj?p=preview

**Comment by spongessuck** [comment]
I'm not sure what you mean- it seems to work for me. What are you trying to do?

**Comment by pucchur** [comment]
I mean two say in the range option how can I have the start and end date as variable in controllers

**Comment by spongessuck** [comment]
You can access them from the `selectedDates` array individually, but they aren't assigned to any variables by default.

    var startDate = Math.min.apply(null, $scope.selectedDates);
    var endDate = Math.max.apply(null, $scope.selectedDates);
