### ISSUE TITLE
Date-disabled not working

### ISSUE THREAD

**Issue by zine56** [spongessuck/gm.datepickerMultiSelect#33]
hello, please i need help with the datepicker, i need to make sure the user is not able to select a second date greater than the first date , i'm quite new to angular so pls help me if you can :|

**Comment by spongessuck** [comment]
You need to implement the `date-disabled` attribute.

    <uib-datepicker ng-model='activeDate' multi-select='selectedDates' date-disabled='disabled(date)'><uib-datepicker>

And in your controller:

    $scope.disabled = function(date) {
        if($scope.selectedDates.length > 0)
            if(date > $scope.selectedDates[0])
                return true;
        return false;
    }

BTW this really is a question you should post on [StackOverflow](http://www.stackoverflow.com), since it has nothing to do with this module.

**Comment by spongessuck** [comment]
My example won't work- selectedDates isn't updated before the `date-disabled` function fires. Will release a fix soon.

**Comment by zine56** [comment]
oh :o much appreciated, thanxs

**Comment by spongessuck** [comment]
v1.0.9 resolves the issue. My example should work now. Also changed title to reflect actual issue.

**Comment by techSavvySaahil** [comment]
Hi @spongessuck : I'm unable to disable dates.
I've added the attribute 'date-disabled'.
Even when I simply write true in its value, the dates aren't getting disabled.
And I've tried by a function as well.
I tried this in your plunker also.
http://plnkr.co/edit/TKpkDe5I8J7jcET7p7JE?p=preview
But nothing seems to be working.

**Comment by spongessuck** [comment]
@techSavvySaahil You're not doing it right.

Your plunker is using UIBootstrap 1.3.3. Somewhere along the line, they changed how `date-disabled` is configured. You now have to define the function as a property that's passed to `datepicker-options`. See this plunk for a working example:

http://plnkr.co/edit/N3llBEysR0LWsnefb1wx?p=preview
