### ISSUE TITLE
Not able to get selected dates

### ISSUE THREAD

**Issue by zaalbarxx** [spongessuck/gm.datepickerMultiSelect#34]
Hi!
I have the problem with accessing selected dates from anywhere. I tried with different versions of ui-bootstrap(0.13 and 0.14) and with Angular 1.4.7. My view html looks like this
``<uib-datepicker ng-model='vm.request.selectedDate' class="multi-datepicker" multi-select select-range="false"></uib-datepicker>``
The ``ng-model`` value is getting updated, but only to single value(currently selected date, and yes, I know that's ok). But I just cannot access selected dates at all. I am using ``controller as`` syntax but even with standard one it just does not seem to work. I was able to make it work only after I changed ``scope.selectedDates`` to ``scope.$parent.selectedDates`` in your code.  I don't see two-way binding anywhere in the code. As far as I understand the data is not bound to the model provided in ``multi-select`` attribute, its just hardcoded ``selectedDates`` value on scope ? Any idea about all of this ?

**Comment by spongessuck** [comment]
You need to assign the `mutli-select` property to an array in your controller. And you don't have to assign select-range if you're not using that feature.

**Comment by zaalbarxx** [comment]
I've tried it before with no luck, but this time it actually worked. Thanks. Now I have one more problem, I have two datepickers on one page and even though one of them does not have ``multi-select`` attribute it still becomes multiselect. I gave both of them different ng-model, but it does not solve the problem. I saw some issue regarding this problem, is it already fixed ?

**Comment by spongessuck** [comment]
Are you using the latest release (v1.0.9)?

**Comment by zaalbarxx** [comment]
Yes, I use the most recent version.

2015-11-02 17:11 GMT+01:00 spongessuck <notifications@github.com>:

**Comment by zaalbarxx** [comment]
Here is the plunker for this
http://plnkr.co/edit/BrGDDEeo38ZPpQtYJB7j?p=preview

**Comment by zaalbarxx** [comment]
Actually there is one more problem, the minified(built) file is still old :) Should I make PR or you'll do it by yourself ?

**Comment by spongessuck** [comment]
Doh! Should be fixed now.
