### ISSUE TITLE
Is it possible to change the styling of one, or many days?

### ISSUE THREAD

**Issue by rj93** [spongessuck/gm.datepickerMultiSelect#36]
I am using the date picker as a way to display an overview (no interaction from the user) of when something has happened to that day. The dates selected are created at runtime and I was wondering if it was possible to change the class of a certian day?

For example:
![dates](https://cloud.githubusercontent.com/assets/6817539/11841853/dd17f5d8-a3f7-11e5-990f-b1d342c7f69d.png)

**Comment by spongessuck** [comment]
Yes. Check out the `custom-class (date, mode)` attribute:

https://angular-ui.github.io/bootstrap/#/datepicker
