### ISSUE TITLE
Is there any option to disable dates earlier to current date?

### ISSUE THREAD

**Issue by tirumalavasu** [spongessuck/gm.datepickerMultiSelect#41]
I am using this to multiselect dates in my project, can you help me to disable the dates earlier to current date. It would be better if we a have that option to the directive.

**Comment by spongessuck** [comment]
Yes, this feature is included with the datepicker directive. Check out the `date-disabled` attribute of the datepicker in earlier UI Bootstrap versions, or the dateDisabled attribute of the datepicker-options object in the newest version.

**Comment by tirumalavasu** [comment]
I have tried to add options to this directive, but no luck. Could anyone help me with this?
Please find the code here

http://plnkr.co/edit/SkFn2w?p=preview

1. I need to hide weeks (showWeeks: false)
2. I need to disable the dates earlier to current date. So that user can able to select from today only.

Thanks in advance.

**Comment by spongessuck** [comment]
You're using an older version of UI Bootstrap (v0.14.x) which hasn't introduced the `datepicker-options` attribute yet. You need to set the attributes individually on the element.

http://plnkr.co/edit/XEsNQtXGwoRvTxcsz3sM?p=preview
