### ISSUE TITLE
How to disable past dates?

### ISSUE THREAD

**Issue by chauhanapoorva2** [spongessuck/gm.datepickerMultiSelect#45]
i am not able to disable past dates and also i want to disable current date after a particular time. please let me know to achieve this. i m new on angular.

**Comment by spongessuck** [comment]
This isn't an issue with this module.

If you post a demo I might point you in the right direction.

**Comment by chauhanapoorva2** [comment]
This is first time i m using angular js so i m totally a new born baby in angular js. please help me for resolving this issue. i want to disable aal dates before current date and current date should be disable after a perticular time in current date like after 9PM current date should be disable user can not select current deate after 9PM. please help me to resolve this.
you can visit http://divinewater.in/bisleri-20-ltr-jar for demo i used your multi date picker
here is code
`(function(angular) {
	'use strict';
	
	angular.module('app', ['gm.datepickerMultiSelect'])
	.controller('AppCtrl', function() {
		this.activeDate;
		this.selectedDates = [new Date().setHours(0, 0, 0, 0)];
		this.removeFromSelected = function(dt) {
		this.selectedDates.splice(this.selectedDates.indexOf(dt), 1);
		}
	});
})(window.angular);


    <div class="form-group"  ng-app="app"  ng-controller='AppCtrl as app' style="clear:both;">
   <uib-datepicker ng-model='app.activeDate' multi-select='app.selectedDates' select-range='{{app.type=="range"}}'></uib-datepicker  class="form-group col-sm-6">
        
          <div class="form-group col-sm-12">
          <h3>Selected Dates:</h3>
                <div ng-repeat='d in app.selectedDates | orderBy' class="form-group col-sm-4" style=" float:left; padding-right:0px;">
               <input type="text" ng-readonly='true' value="{{d | date : 'mediumDate'}} " name="delivery[]" min-date="'2016-03-10'" style="background:none; border:none; width:100px" />
                <button class='btn btn-xs btn-warning' style='margin:5px; background:#009EFF;' ng-click='app.removeFromSelected(d)'>Remove</button>
              </div>
            </div>
            
              </div>`

**Comment by spongessuck** [comment]
You'll just need to do a calculation to set `min-date` based on the current time.

For example:

    var today = new Date();
    if(today.getHours() > 21) {
        this.minDate = today.setHours(24);    // After 9 PM - set minDate to tomorrow
    } else {
        this.minDate = today;
    }

Be aware that in this example `today` will be the current *local* time based on the client's OS, which could be anything depending on where they are and if their time is set correctly. If you really want to keep users from selecting days based on the time of day, you should send the exact universal time you want to cut off orders from your server, and also validate the times the client sends to the server.
