### ISSUE TITLE
single date selection using gm.datepickerMultiSelect

### ISSUE THREAD

**Issue by harikrishna149** [spongessuck/gm.datepickerMultiSelect#46]
Hi, I am Harikrishna. I am working in a project using gm.datepickerMultiSelect. I want to select single date using gm.datepickerMultiSelect. How can i select single date only. Please help me asap.

Thanks
Harikrishna

**Comment by spongessuck** [comment]
Just use the regular UI Bootstrap datepicker. You don't need this module if you don't want to select more than one date.
