### ISSUE TITLE
Dates not selecting when ng-model-options timezone set to UTC

### ISSUE THREAD

**Issue by spongessuck** [spongessuck/gm.datepickerMultiSelect#47]
Need to have directive check for this value and adjust its calculations.

**Comment by hummorsa** [comment]
I am having the same issue, any ideas ? Thanks.

**Comment by spongessuck** [comment]
I have a new version in the works that should solve this problem, but it has breaking changes relating to filling the `selectedDates` programatically. Watches should check it out. If it seems to do the trick, I'll release a new version.

http://plnkr.co/edit/MFoWLc?p=preview
