### ISSUE TITLE
Parent directives options dont seem to work

### ISSUE THREAD

**Issue by SolStis86** [spongessuck/gm.datepickerMultiSelect#50]
When trying to set datepicker-options on this extension the original functionality doesnt seem to work... ie setting a minDate with 

scope.options = {minDate: new Date()}

<uib-datepicker datepicker-options="options">

doesnt work...

Im not sure if theres some additional logic in the linking that needs to be added?

Ill look into it and see if i can find out unless anyone else knows?

**Comment by spongessuck** [comment]
Can you post a demo? This directive shouldn't affect `datepicker-options`.

**Comment by weequ** [comment]
I have the same issue. Trying to make weeks start from monday with
`datepicker-options='{startingDay: 1}'`
, but they still start from sunday.

**Comment by spongessuck** [comment]
As I said, I need to see a demo to help. It works fine for me:

http://plnkr.co/edit/4xgeDQ?p=preview

**Comment by TdyP** [comment]
I'm not able to show a demo but I do have the same issue in my project. `datepicker-options='{startingDay: 1}'` is just ignored.

One thing that might be related, I can't use the `uib-datepicker` directive:
```
<uib-datepicker ng-model="activeDate" multi-select="model.days" show-weeks="false" min-date="minDate" datepicker-options="{startingDay: 1}"></uib-datepicker>
```
won't show anything
If I use `datepicker` instead, it works fine, with multiselect, etc.

Do you have any idea of what might cause this behavior? Any conflict with original datepicker or something?

FYI:
```
"angular": "1.5.6",
"angular-ui-bootstrap": "1.3.3",
"gm.datepickerMultiSelect": "gm.datepicker-multi-select#1.0.10"
```

Thanks!

**Comment by spongessuck** [comment]
If you can't show a demo, I can't help.

See my plunk above for a working example with `startingDay` and `uibDatepicker`.
