### ISSUE TITLE
How to change background-color of previous and next arrow button on calendar 

### ISSUE THREAD

**Issue by sheshnathiicmr** [spongessuck/gm.datepickerMultiSelect#53]
Thanks,  it's working fine, just i need to change color of previous and next arrow button on calendar.

**Comment by spongessuck** [comment]
Questions not relating to this module should be asked elsewhere, i.e. stackoverflow.com.

However, I'm feeling nice today, so: you can do it with CSS rules:
``` css
.uib-daypicker .uib-left {  /* left button */
    ...
}

.uib-daypicker .uib-right {  /* right button */
    ...
}
```
