### ISSUE TITLE
Styling of the selected date buttons

### ISSUE THREAD

**Issue by sumiangi** [spongessuck/gm.datepickerMultiSelect#54]
Hey @spongessuck 
i know this is an existing issue. Just wanted to know whether this has been fixed for the latest UI bootstrap in any recent release ?

Thanks in advance..

**Comment by spongessuck** [comment]
Hi, @sumiangi.

If you could post a demo of the problem, that would be helpful.

**Comment by sumiangi** [comment]
Hey @spongessuck 

Let me clarify.
Its just that for uib datepicker popup if i am selecting multiple dates then those dates should be highlighted as selected if i am again opening the popup.

please let me know if you still need the demo. I will create a Plunk.

Thanks in advance.

**Comment by spongessuck** [comment]
Yes, please post a plunk and I'll check it out.

**Comment by spongessuck** [comment]
Closed due to lack of activity.
