### ISSUE TITLE
Does not work with AngularUI 2.x.x

### ISSUE THREAD

**Issue by jansauerbrey** [spongessuck/gm.datepickerMultiSelect#55]
Hi,

since the uib-datepicker directive seem to have changed in Angular UI Bootstrap 2.x.x, the gm.datepickerMultiSelect does not work with the newer version. At least I didn't get the example working. The picker just doesn't show up anymore.

Any chance to adapt the datepickerMultiSelect to the new version?

Thanks,
Jan

**Comment by spongessuck** [comment]
Of course it doesn't work with Angular 2. There needs to be a complete rewrite for this to work in Angular 2.

**Comment by spongessuck** [comment]
Oh nevermind I misread the issue. If you make a plunk using the newest UI bootstrap I'll take a look.

**Comment by jansauerbrey** [comment]
Hi, here is your example with updated versions of all libaries.

http://plnkr.co/edit/fgGQtz?p=preview

I also included the datepicker twice, once as tag and once as attribute. Neither seems to work.

**Comment by spongessuck** [comment]
It has to do with the custom template that makes the dates highlight properly- something must have changed and it doesn't work anymore. If you remove the custom template, the datepicker appears but only the last selected date is highlighted.

**Comment by jansauerbrey** [comment]
Yes you are right. the template needs to be changed to something like this:

`<div class="uib-datepicker" ng-switch="datepickerMode" role="application" ng-keydown="keydown($event)">
    <div uib-daypicker ng-switch-when="day" tabindex="0" template-url="multi-day.tpl.html"></div>
    <div uib-monthpicker ng-switch-when="month" tabindex="0"></div>
    <div uib-yearpicker ng-switch-when="year" tabindex="0"></div>
</div>`

changeing uib-... to an attribute instead of a tag will give me the solution :)

**Comment by spongessuck** [comment]
So were you able to get this to work?

**Comment by spongessuck** [comment]
Please see the following plunk on getting this working with UI Bootstrap 2.x.x.

It involves removing the custom templates and using `customClass` in `datepicker-options` instead:

http://plnkr.co/edit/7rKzFo?p=preview
