### ISSUE TITLE
Main / Max Dates not working

### ISSUE THREAD

**Issue by SolStis86** [spongessuck/gm.datepickerMultiSelect#56]
Adding datepicker-options to the directive doesnt set the min and max allowable dates...  is there an enhancement required...?

**Comment by spongessuck** [comment]
No. Please post issues not related to this module on the UI Bootstrap repo, or ask a question on stackoverflow.com.

**Comment by SolStis86** [comment]
It works using the native ui bootstrap

Kind Regards

James Fairbrother
MV Digital

+44 (0)7803 824 804 | mvdigital.co


---- On Tue, 11 Oct 2016 14:01:29 +0100 notifications@github.com wrote ----

No. Please post issues not related to this module on the UI Bootstrap repo, or ask a question on stackoverflow.com.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of MV Digital.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.

**Comment by spongessuck** [comment]
This module doesn't work properly on UI Bootstrap 2.x.x. It works fine on 1.x.x with a custom daypicker template, and doesn't interfere with min/max date.
