### ISSUE TITLE
How to force a visual update to calendar when removing some of the selected dates

### ISSUE THREAD

**Issue by brainframe-me** [spongessuck/gm.datepickerMultiSelect#57]
In the example code you can select some dates, which will then appear below with a remove button.
On selection they are also highlighted in blue on the calendar. But if one modifies the model by clicking on the remove button of one of the dates below, then nothing happens in the calendar view.

So the main problem is, how can I force a refresh from outside the directive that the calendar needs to refresh its view based on the new model data.

Thank you in advance,

**Comment by spongessuck** [comment]
Which example are you seeing this in?

**Comment by brainframe-me** [comment]
I started with the latest example in your repository: https://github.com/spongessuck/gm.datepickerMultiSelect/blob/master/examples/angular.1.5.6-bootstrap.1.3.3.html
And then started adding to make compatible with my UI Bootstrap 2.x code with bower:
```
    "gm.datepickerMultiSelect": "gm.datepicker-multi-select#^1.0.10",
    "ui-bootstrap": "^2.2.0"
```

Here is current setup:

```
  // Select range or single date selection
  <md-switch class="col-lg-6" ng-model="dateSelectorType" aria-label="{{ 'Selection type' | translate}}" ng-true-value="'individual'" ng-false-value="'range'">
  {{ 'Selection type' | translate}}:
  <span ng-show="dateSelectorType==='individual'">{{ 'Individual dates' | translate}}</span>
  <span ng-show="dateSelectorType==='range'">{{ 'From-To range' | translate}}</span>
  </md-switch>

 // The actual date picker
  <div
  uib-datepicker
  ng-model='activeDate'
  multi-select='selectedDates'
  select-range='{{dateSelectorType=="range"}}'
  datepicker-options='dateSelectorOptions'></div>

// The remove part
   <div class="row" ng-repeat='d in selectedDates | orderBy'>
     <md-button  ng-click='removeFromSelected(d)' >
       <span class="glyphicon glyphicon-trash"></span>
    </md-button>
    {{d | date : 'EEE, MMM d, yyyy'}}
  </div>
```

Javascript (changed this to scope, so I can use it in my controller) :
```
  $scope.activeDate = '';
  $scope.selectedDates = [new Date().setHours(0, 0, 0, 0)];
  $scope.dateSelectorType = 'individual';

  $scope.dateSelectorOptions = {
    startingDay: 1,
    minDate: new Date(),
    // As mentioned in your readme this needs to be done for UI Bootstrap 2.x
    customClass: function (data) {
      if ($scope.selectedDates.indexOf(data.date.setHours(0, 0, 0, 0)) > -1) {
          return 'selected';
      }
      return '';
    }
  };

  $scope.removeFromSelected = function (dt) {
    $scope.selectedDates.splice($scope.selectedDates.indexOf(dt), 1);
  };
```

All works great, except the updates made outside the directive.

The main problem seems to be that the directive creates child scopes which hold the selectedDates data. When removing one of the dates by clicking on the remove button, the date is removed from the list (so main scope), but the calendar does not update (child scope). Only when selecting a new date in the calendar, the previously removed element is also gone which means that the calendar only updates its child scopes when directly interacting with it, and not when changes occur to the main model.

Any ideas?

**Comment by spongessuck** [comment]
I won't be able to check this out today. You can try calling `$scope.apply()` at the end of `$scope.removeFromSelected`.

**Comment by brainframe-me** [comment]
No, this was the first thing I tried. And then I get:
[$rootScope:inprog] $apply already in progress

Even when I put in a delay which always solves this 'already in progress', nothing updates

    setTimeout(function () {
      $scope.$apply();
    }, 500)

I see you refer to your app and controller in the following way:
ng-app="app"
ng-controller='AppCtrl as app'

And then in your models "app.varname"

Where I just use
ng-app="app"
ng-controller='Controllername'
models: "varname" without anything which works for everything I do

Could that have something to do with it? Any other ideas?

**Comment by spongessuck** [comment]
OK, I found a workaround. You need to re-assign `activeDate` for the datepicker to call `customClass` again. In this plunk, you'll see I assign it to the removed datetime as you remove selected dates:

http://plnkr.co/edit/7rKzFo?p=preview

**Comment by brainframe-me** [comment]
Great, that worked, thanks!
